### ISSUE TITLE
cluster manager gui not able to start yarpserver with --ros option

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#1056]
if `--ros` option is checked in the  gui, `icub-cluster.py` will fail to launch yarp server.

**Comment by aerydna** [comment]
found and fixed on the r1-base.

- by launching the command via ssh (so with a "not interactive" shell) only our .bashrc_iCub is sourced 
- If the ROS_MASTER_URI is defined in .bashrc_iCub the problem does not occour
- if (as usuallly is) the ROS_MASTER_URI is defined in the ros's "setup.bash", in a not interactive shell that file is not sourced, ROS_MASTER_URI ends up not defined and yarpserver launch fails.
fixed by sourcing the ros setup.bash before returning from the source .bashrc operation.

eg.
```
# If not running interactively, don't do anything <-- exept sourcing setup.bash
case $- in
    *i*) ;;
      *)source blablabla/setup.bash # <--- this line fix the issue
         return;;
esac
```

@mbrunettini does this sounds good to you?
