### ISSUE TITLE
yarpmanager error when yarpserver is not found is not clear

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#1536]
When the yarpserver is not found, the yarpmanager prints the following message:
~~~
[ERROR]Manager::Cannot contact the NameClient 
~~~
As this is a common error for newbies, I propose to at least add a reference to `yarpserver` in the message (for a newbie, knowing that the NameClient is the `yarpserver` is not obvious). 

cc @Nicogene

**Comment by Nicogene** [comment]
I agree with you. 👍 
This error is triggered when you try to contact the name client but the comunication fails because `yarpserver` is not running.
I can add `NetworkBase::checkNetwork()` before this check, so if the server is not running it avoids to contact the `NameClient` and displays a proper error message.

Thanks for reporting 👌
