### ISSUE TITLE
Lua bindings `lua/argcargv.i` not being installed

### ISSUE THREAD

**Issue by jgvictores** [robotology/yarp#1776]
**Bug description**
`bindings/lua/argcargv.i` is required by `bindings/yarp.i`, but is not being installed by `bindings/CMakeLists.txt`.

**Location in source code**
Required at [current `master` bindings/yarp.i#L36](https://github.com/robotology/yarp/blob/d1153351a9163dabf687509d7565d1a34d7306f2/bindings/yarp.i#L36), not present at [current `master` bindings/CMakeLists.txt#L91](https://github.com/robotology/yarp/blob/d1153351a9163dabf687509d7565d1a34d7306f2/bindings/CMakeLists.txt#L91)

**Why this is not caught by tests**
Because in tests, bindings are compiled via files in source code, not from installed files.

**Relevance for finding a solution**
For bindings to be compiled from the build material (typically for such files to be found by the windows installer). 
Additionally: there is a `Ensure that bindings can be built from installation` card by @drdanz for [YARP v3.0.1](https://github.com/robotology/yarp/projects/7). :slightly_smiling_face:

**Requirement for solution**
Note that we cannot simply add `lua/argcargv.i` in the mentioned `CMakeLists.txt` line, as it will be installed as simply `argcargv.i` (loses `lua/`). Must me done thoughtfully. :smile:

**Comment by drdanz** [comment]
Since 65e39c94dbf399f7ede27a77d3ffad0d87710154, travis is building the bindings (including lua) from the install directory, and it seems to work, see for example [this build](https://travis-ci.org/robotology/yarp/jobs/399192161)... 

The file [is installed](https://travis-ci.org/robotology/yarp/jobs/399192161#L9975) in `share/yarp/bindings/lua/argcargv.i`, by
https://github.com/robotology/yarp/blob/efba777a8be6e461196064dd8570c38b60930d49/bindings/CMakeLists.txt#L97-L105


I'm closing this, please re-open if I'm wrong.
