### ISSUE TITLE
Support of hexadecimal representation in Value

### ISSUE THREAD

**Issue by Nicogene** [robotology/yarp#2120]
It would be nice to have function in `Value` such as, `asHex()`, `toHex()` `isHex()`.

**Comment by drdanz** [comment]
This goes beyond the scope of `Value`, the other methods are about the actual value type, this is a "display" feature. `asHex()` and `isHex()` do not make any sense, since there is no "hex int" type. `toHex()` could have a reason to exist, but it would just return a string". And then you have to deal with this kind of issues:

 * `ABCDEF` or `abcdef`?
 * `0x`, `0X`, or nothing?

This kind of printing methods are partially in `NetType.{cpp,h}`, and partially scattered around the code (see the float printing). It would be a good idea to move all of them in the same place (no, `NetType` does not mean anything even partially related to this meaning, therefore it makes no sense to me to keep them there). But this is another issue, therefore I'm closing this as "wontfix".
