### ISSUE TITLE
opencv_grabber should use YARP_cv utilities

### ISSUE THREAD

**Issue by Nicogene** [robotology/yarp#2161]
`opencv_grabber` converts the `cv::Mat` to a `yarp::sig::image` with a `memcpy`.

https://github.com/robotology/yarp/blob/0ac66ed8b703eecd2207e24dbff4432008761b7b/src/devices/opencv/OpenCVGrabber.cpp#L196-L200

We should use instead `fromCvMat` (introduced in #1932) that does not involves copies:

https://github.com/robotology/yarp/blob/0ac66ed8b703eecd2207e24dbff4432008761b7b/src/libYARP_cv/src/yarp/cv/Cv-inl.h#L90-L112

**Comment by PeterBowman** [comment]
I'm afraid it is not viable, or at least not as straightforward as a simple invocation of `yarp::cv::fromCvMat`. Since no copies are involved, but rather `yarp::sig::Image` holds a pointer to a memory location managed by an instance of `cv::Mat`, the lifetime of the latter is critical. However, this `cv::Mat` dies as soon as the `getImage` method is exited, therefore the wrapping `grabberdual`  device attempts to forward a bogus `yarp::sig::Image` over the network (the memory location of the desired image may be erased at that point).

**Comment by drdanz** [comment]
Fixed by @PeterBowman in #2713
