### ISSUE TITLE
cannot launch the wholebodydynamics and gravitycompensater when doing the redball demo

### ISSUE THREAD

**Issue by Yujia-Zhang0913** [robotology/yarp#3036]
Hi, I follow the guide of tech-doc but I still cannot launch the wholebodydynamics.
The error is like the picture below. I do not know why.
![Screenshot from 2023-10-26 12-56-29](https://github.com/robotology/yarp/assets/73634487/81228884-7245-41c1-b972-e26bf681a3d6)
Can you help me?
Moreover, sometimes the wholebodydynamics can be launched, but the gravitycompensater cannot be launched. The inertial part cannot be connect(Since now I cannot launch the dynamics, the error of gravitycompensator I cannot reproduce, I don't have the screenshot of this error)
Really thanks.

**Comment by traversaro** [comment]
Hello @Yujia-Zhang0913 , this question seems to be a more general question on iCub setup, and not YARP-specific. Can you open a question in https://github.com/orgs/robotology/discussions/categories/q-a ? Thanks!

**Comment by Yujia-Zhang0913** [comment]
Sorry to bother you again, I want to install yarp on my own laptop. And follow the guide in this link [https://www.yarp.it/latest/install_yarp_linux.html](url), and when I check the installion, it report segment fault (core dump) like image below.(the error is reported in Chinese, in English it is segment fault (core dump) ) 
![2023-10-26 21-39-59 的屏幕截图](https://github.com/robotology/yarp/assets/73634487/3dd69bee-f689-4a0e-96e1-1a2474bb8d43)
And when I run yarpserver and yarp read /portread, it is Ok. 
Thanks for helping me!

**Comment by randaz81** [comment]
Dear @Yujia-Zhang0913 , I'm supposing that you installed Yarp via apt-get. 
Unfortunately, apt binary packages are currently no longer maintained (you can check the release you installed with the `yarp --version` command, the latest stable version is Yarp 3.8). So my recommendation is to build Yarp from source in order to get the latest stable version.  
However, since I imagine you are not interested in Yarp only, but in the whole robotology package, which is required to control an iCub robot, I'd advise you to follow the robotology-superbuild installation instructions: https://github.com/robotology/robotology-superbuild
