### ISSUE TITLE
Get rid of yarp::os::Module

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp#576]
`yarp::os::Module` class is _practically_ deprecated in favor of `yarp::os::RFModule`, hence we should consider removing it.

Before removing, we need to update `yarpdataplayer-qt` to the use of `yarp::os::RFModule` (/cc @vtikha).

Address https://github.com/robotology/icub-main/issues/191 as a pre-requisite.
See also #432.

/cc @alecive

**Comment by vtikha** [comment]
This is not actually a module per se...cleaned it up

**Comment by pattacini** [comment]
Actually, this ticket was concerned with the idea of drastically removing the class yarp::os::Module from Yarp. Thus, reopening for discussion.

**Comment by vtikha** [comment]
I am removing the `yarpdataplayer-qt` tag which is erroneous in this case.

**Comment by traversaro** [comment]
I think we should start to use the `YARP_DEPRECATED` introduced some time ago that is now disable by default, so we can induce warnings on 3rd party code that uses classes/function that we want to deprecated. `yarp::os::Module` seems to be a good use case for this.

**Comment by vtikha** [comment]
:+1:

**Comment by drdanz** [comment]
+1 for marking it ``YARP_DEPRECATED``. I would also remove it from ``yarp/os/all.h`` and a deprecated warning when including the ``yarp/os/Module.h`` header.
Actually yesterday I tried to do it, but I got stuck with a stupid [issue](https://stackoverflow.com/questions/32463839/inheritance-from-deprecated-class) with gcc.

Also, even if we don't support it, if it is not a long task, I think we should get rid of it in yarpdataplayer-gtk, so that we can theoretically remove the class any time without breaking YARP itself.

**Comment by lornat75** [comment]
Fine with me although I would consider it a minor issue.

**Comment by pattacini** [comment]
We should be now safe: we no longer make use of `yarp::os::Module` within all the projects we manage (`icub-main`, `icub-basic-demos`, `iol` ...).

@drdanz are you willing to declare `yarp::os::Module` deprecated in the proper way you guys mentioned?

**Comment by drdanz** [comment]
Sure! Assigning it to myself.
