### ISSUE TITLE
RFModule online documentation polluted

### ISSUE THREAD

**Issue by gsaponaro** [robotology/yarp#578]
Hi, in the online documentation at http://wiki.icub.org/yarpdoc/classyarp_1_1os_1_1RFModule.html I noticed this line under a few functions, it probably should not be there, right?

![rfmodule_doc](https://cloud.githubusercontent.com/assets/6716962/9666405/c1bcdcf8-526d-11e5-952f-e3de3649014b.png)

**Comment by pattacini** [comment]
It's normal, since we have this [**`KinectThread`**](https://github.com/robotology/yarp/blob/master/src%2Fmodules%2Fkinect%2FOpenNI%2FTEST%2Fmain.cpp#L30) class in yarp.

Then, why there's an inheritance from `yarp::os::Thread` and `yarp::os::RFmodule` is at least questionable (`yarp::os::RFModule` is a thread in the end).

**Comment by gsaponaro** [comment]
I see, thanks.
